environment: TESTE
debug: false

spring:
  servlet: 
    multipart:
      enabled: true
      file-size-threshold: 10KB
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:h2:mem:movies
    username: sa
    password: 123123
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings.trace: true 
server:
  port: 8080
  timezone: ${server.config.timezone:America/Sao_Paulo}
  name: NONE
logging:
  pattern:
    dateformat: ${server.config.logging.pattern:yyyy-MM-dd HH:mm:ss.SSS,America/Sao_Paulo}
#  level:
#    ROOT: DEBUG


